name: Gitflows stats CI

on:
  push:
  pull_request:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.15.x]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: |
          npm ci
      - name: Execute tests
        run: |
          npm run test

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.15.x]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Node js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: |
          npm ci
      - name: Build module
        run: |
          npm run build
    needs: test

  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: node
          package-name: gitflows-stats
          changelog-types: '[{"type":"feat","section":"Features","hidden":false},{"type":"fix","section":"Bug Fixes","hidden":false},{"type":"chore","section":"Miscellaneous","hidden":false}]'
      - uses: actions/checkout@v3
        if: ${{ steps.release.outputs.release_created }}
      - name: Set up Node js
        if: ${{ steps.release.outputs.release_created }}
        uses: actions/setup-node@v3
        with:
          registry-url: "https://registry.npmjs.org"
      - name: Install and build
        if: ${{ steps.release.outputs.release_created }}
        run: |
          npm ci
          npm run build
      - run: npm publish
        if: ${{ steps.release.outputs.release_created }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    needs: build
